{
 "title": "Observed Microsample",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusds", "label": "Prometheus", "query": "prometheus" },
   { "name": "lokids", "label": "Loki", "query": "loki" },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid},juju_model)"
    }
   },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_application=~\"$juju_application\",juju_model_uuid=~\"$juju_model_uuid\"},juju_unit)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Microsample API Calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsample_calls_total{juju_application=\"observed\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_application}}"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsample_calls_total{juju_application=\"observed\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Calls per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(microsample_calls_total{juju_application=\"observed\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[2m])/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Microsample API calls \"404\"",
   "type": "logs",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_application=\"observed\", juju_unit=~\"$juju_unit\"} |= \"microsample\" |= \"404\""
    }
   ]
  },
  { "title": "Alert list ", "type": "alertlist", "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 } },
  {
   "title": "Syslog",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/syslog\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_application=\"observed\", juju_unit=\"observed/0\"} |= \"\""
    }
   ]
  }
 ]
}