##  Alertmanager example using both PagerDuty and Slack
##  Prometheus documentation: https://github.com/prometheus/alertmanager/blob/main/docs/configuration.md
##  Pagerduty guide: https://www.pagerduty.com/docs/guides/prometheus-integration-guide/
global:
  http_config:
    follow_redirects: true
    enable_http2: true
    tls_config:
        insecure_skip_verify: false
  resolve_timeout: 1m
  pagerduty_url: https://events.pagerduty.com/v2/enqueue # Default api-url
  slack_api_url: '<incomming-webhook-api-url>' # Default api-url

route:
  receiver: 'slack-notifications'
  group_by: ['alertname', 'severity']
  group_wait: 0s
  group_interval: 1m
  repeat_interval: 1m
  routes:
  - match:
      severity: 'error|warning'
    receiver: 'slack-notifications'
  - match:
      severity: 'critical'
    receiver: 'pagerduty'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertmanager'
    send_resolved: true
    username: 'Alertmanager'
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: |-
          [{{ .Status | toUpper }}{{if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{$label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
    text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    http_config:
      follow_redirects: true
      enable_http2: true
      tls_config:
        insecure_skip_verify: true
      authorization:
        credentials: '<xoxb-slack-bot-api-token>' # Alertmanager v 0.22 and later
    api_url: https://slack.com/api/chat.postMessage # This overrides default api-url
    
    ## Alertmanager version Pre-0.22
    # slack_configs:
    # - send_resolved: true
    #   channel: "#my-channel"
    #   api_url: https://slack.com/api/chat.postMessage
    #   http_config:
    #     bearer_token: <xoxb-slack-bot-api-token>

- name: 'pagerduty'
  pagerduty_configs:
  - service_key: '<service-key>'
    send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
      tls_config:
        insecure_skip_verify: true
    #api_url: <api-url> # If other api-url is needed.